name=GUIML
version=0.0.1
author=AR Engineering
maintainer=AR Engineering
sentence=Generic User Interface and Menu Library. A open source library to easily implement menu, user interfaces and interactive applications using the U8G2 library from Olikraus.
paragraph=Arduino Uno, Nano, Mega 2560
category=User interfaces
url=
architectures=Atmel
includes=U8g2lib.h
